# Generated by Django 4.1.7 on 2023-03-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='country',
            field=models.CharField(default='Kazakhstan', max_length=255),
        ),
    ]
